NIRS/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import TemplateView
from auths import views
from logic import views as logic_views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', logic_views.index, name='home'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^add_exp/$', logic_views.add_exp, name='add_file'),
    url(r'^repeat_exp/(?P<exp_id>[0-9]+)/$', logic_views.repeat_exp, name='repeat_exp'),
    url(r'^check_exp/$', logic_views.check_exp, name='check_exp'),
    url(r'^check_exp/(?P<exp_id>[0-9]+)/$', logic_views.check_exp_by_id, name='check_exp_by_id'),
    url(r'^check_result/(?P<exp_id>[0-9]+)/$', logic_views.check_result_by_id, name='check_result_by_id'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^confirm_email/$', TemplateView.as_view(template_name='email_confirm.html'),
        name='email_confirm'),
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),

    # url(r'^settings/account/$', views.UserUpdateView.as_view(), name='my_account'),
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
        name='password_change'),
    url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
        name='password_change_done'),

    url(r'^admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nirs/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^auth/', include('auths.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('logic.urls')),
]

logic/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField


def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.username, filename)


class Device(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    process_node = models.IntegerField()
    supply_voltage = models.FloatField()
    resistance = models.FloatField(default=1.5e4)
    capacitance = models.FloatField(default=1e-15)

    def __str__(self):
        return '{0}\nnode: {1}\nvoltage: {2}\nresistance: {3}\ncapacitance: {4}'.format(self.name, self.process_node, self.supply_voltage, self.resistance, self.capacitance)


class Experiment(models.Model):
    # device
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    device = models.ForeignKey(
        Device,
        default=None,
        on_delete=models.CASCADE,
        blank=True
    )

    # models
    par1 = models.FloatField(null=True)
    par2 = models.FloatField(null=True)
    model_type = models.CharField(max_length=10,
                                  choices=(('point', 'Точечная модель'),
                                           ('voltage', 'Модель напряжений')))
    sim_type = models.CharField(max_length=15,
                                choices=(('monte_carlo', 'Монте-Карло'),
                                         ('analytical', 'Аналитический')))

    geometry = models.CharField(max_length=15,
                                choices=(('disc', 'Диск'),
                                         ('sphere', 'Сфера')))

    spectre = ArrayField(ArrayField(models.FloatField()), null=True)
    experimental_data = ArrayField(ArrayField(models.FloatField()), size=2, null=True)

    # phys
    diff_coefficient = models.FloatField(default=12.)
    ambipolar_diff_coefficient = models.FloatField(default=25.)

    # accuracy
    trials_count = models.IntegerField(default=20)
    particles_count = models.IntegerField(default=50000)
    let_values_count = models.IntegerField(default=300)

    # let-cross_section
    simulation_result = ArrayField(ArrayField(models.FloatField()), null=True)

    ser = models.FloatField(null=True)

logic/forms.py
from django import forms
from .models import Experiment, Device


class ExperimentForm(forms.ModelForm):
    data = forms.FileField(label='Результаты эксперемента')
    let = forms.FileField(label='Спектр')
    device = forms.ModelChoiceField(queryset=Device.objects.none(), required=False)

    def __init__(self, user, *args, **kwargs):
        super(ExperimentForm, self).__init__(*args, **kwargs)
        self.fields['device'].queryset = Device.objects.filter(user=user.id)

    class Meta:
        model = Experiment
        exclude = ('user', 'simulation_result', 'par1', 'par2', 'spectre', 'experimental_data', 'ser')


class DeviceForm(forms.ModelForm):

    class Meta:
        model = Device
        exclude = ('user',)

templates/includes/form.html
{% load form_tags widget_tweaks %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}


{% for field in form %}
  {% if field.label_tag == '<label for="id_trials_count">Trials count:</label>' or field.label_tag == '<label for="id_particles_count">Particles count:</label>' or field.label_tag == '<label for="id_let_values_count">Let values count:</label>' %}
    <div class="form-group count">
  {% else %}
    <div class="form-group">
  {% endif %}
    {% if field.label_tag == '<label for="id_device">Device:</label>' and status %}
      {{ field.label_tag }}
      {{ field|add_class:'form-control is-invalid' }}
      <div class="invalid-feedback">
        Поле обязательное для заполнения
      </div>
    {% else %}
      {{ field.label_tag }}
      {% render_field field class=field|input_class %}
      {% for error in field.errors %}
        <div class="invalid-feedback">
          {{ error }}
        </div>
      {% endfor %}
    {% endif %}
    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
  {% if field.label_tag == '<label for="id_device">Device:</label>' %}
    <button type="button" class="btn btn-primary btn-sm js-form-new-device form-new-device">Или добавить новый девайс</button>
    <div class="js-form device-form" style="display: none">
    <h5 class="text-center">Новый девайс</h5>
      {% for field in device_form %}
        <div class="form-group">
          {{ field.label_tag }}
          {% render_field field class=field|input_class %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
          {% if field.help_text %}
            <small class="form-text text-muted">
              {{ field.help_text|safe }}
            </small>
          {% endif %}
        </div>
      {% endfor %}
    </div>
  {% endif %}
{% endfor %}